In [1]:
import numpy as np

### 문제1
0이상 100이하의 임의의 정수들로 구성되는 10행 5열의 2차원 numpy array인 ``score``를 생성하시오.

array([[61, 86, 96, 18, 92],
       [35, 39, 73, 71, 81],
       [21, 32, 45, 33,  9],
       [82, 88,  3, 55, 36],
       [92, 85, 96, 45, 67],
       [42, 61,  6, 55, 99],
       [95, 58, 10,  4,  4],
       [78, 73, 94, 28, 78],
       [84, 10, 61, 23, 76],
       [23, 15,  7, 69, 49]])

### 문제2
지금부터 ``score``가 10명의 학생들의 국어, 영어, 수학, 과학, 사회 점수를 뜻한다고 가정하자.

이제 5개 과목의 평균점수를 뜻하는 ``avg_subject`` array(1차원)를 생성하시오. 

array([61.3, 54.7, 49.1, 40.1, 59.1])

### 문제3
학생별 평균점수를 뜻하는 ``avg_student`` array(1차원)를 생성하시오. 

array([70.6, 59.8, 28. , 52.8, 77. , 52.6, 34.2, 70.2, 50.8, 32.6])

### 문제4
10명 중 row의 index가 짝수인 학생은 여학생(index 0 포함), 홀수인 학생은 남학생이라고 할 때, <br>
여학생 전체의 5개과목별 평균점수를 뜻하는 ``avg_female`` array(1차원)을 구하시오.

array([70.6, 54.2, 61.6, 24.6, 49.6])

### 문제5
마찬가지로 남학생 전체의 5개과목별 평균점수를 뜻하는 ``avg_male`` array(1차원)을 구하시오.

array([52. , 55.2, 36.6, 55.6, 68.6])

### 문제6
5개 과목의 표준편차 std_array(1차원)를 생성하시오.

array([29.45318319, 31.86989175, 24.40676136, 29.97932621, 24.6771149 ])

### 문제7
각 과목의 최고점수(max) max_array(1차원)를 생성하시오.

array([ 94,  99, 100,  94,  97])

### 문제 8

 2차원 넘파이 배열에 100명의 (키, 몸무게, 나이)를 저장하고 있다. 
 - 정규분포를 이용하여 자동으로 데이터를 생성
 - 정규분포 생성 시 키는 175, 몸무게는 70, 나니는 22세를 평균으로 하고 표준편차는 10이 되도록 한다
 - 데이터의 실제 평균과 중앙값을 구하기