### 넘파이 설치

In [ ]:
# !pip install numpy

### 넘파이 임포트

In [1]:
import numpy as np

In [2]:
x = np.array([[2, 1, 6],[0, 7, 4],[5, 3, 2]])
print(x)
print(np.sort(x, axis=0)[::-1])

[[2 1 6]
 [0 7 4]
 [5 3 2]]
[[5 7 6]
 [2 3 4]
 [0 1 2]]


In [3]:
a = np.arange(16).reshape(4,4)
print(a,'\n')
print(a[[1,3],:],'\n')
print(a[[1,3],0::2])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 

[[ 4  5  6  7]
 [12 13 14 15]] 

[[ 4  6]
 [12 14]]


### 넘파이 버전 확인  
- `__version__` 넘파이 모듈 임포트 후에 현재 설치된 numpy의 버전 체크가 가능

In [ ]:
import numpy as np
print(np.__version__)

### 넘파이 배열 생성

#### 1) 넘파이 배열 기본 생성

In [ ]:
#리스트로 넘파이 배열(1차원) 생성
import numpy as np
arr1 = np.array([0, 2, 5.5, 7])
arr1

In [ ]:
#리스트로 넘파이 배열(1차원) 생성
import numpy as np
list1 = [0, 2, 5.5, 7]
arr1 = np.array(list1)
print(arr1)

In [ ]:
import numpy as np
a = np.array([1, 2, 3, 4])
print(a)
print(type(a))
print(a.dtype)

b = np.array([1.2, 3, 5.1])
print(b)
print(type(b))
print(b.dtype)

In [ ]:
#리스트로 넘파이 배열(2차원) 생성
import numpy as np
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

In [ ]:
#리스트로 넘파이 배열(2차원) 생성
import numpy as np
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)
print(arr2.shape)
print(arr2.ndim)
arr2.dtype

In [ ]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
print(a, '\n')
print(b, '\n')
print(c, '\n')
print(a[0], b[0][1], c[0][1][1])

In [ ]:
print(a.shape, a.ndim, a.size)
print(b.shape, b.ndim, b.size)
print(c.shape, c.ndim, c.size)

### 넘파이 배열의 데이터 타입(dtype)을 지정하는 두 가지 방법

In [ ]:
a = np.array([1, 2, 3, 4], dtype = np.int32)
print(a)
a.dtype

In [ ]:
a = np.array([1, 2, 3, 4], dtype = 'int32')
print(a)
a.dtype

In [ ]:
a = np.array([1, 2, 3, 4], dtype = 'int32')
print(a)
print(a.dtype)
print(a.astype(float))
print(a.dtype)
b = a.astype(float)
print(b.dtype)

In [ ]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr4 = np.array(data2)
print(arr4)
print(arr4.shape)
print(arr4.dtype)

### 넘파이 배열 생성(초기화)

#### 2) np.zeros()

In [ ]:
import numpy as np
arr = np.zeros(5)
# arr = np.zeros(5,)
arr

In [ ]:
type(arr)

In [ ]:
arr.shape

In [ ]:
arr.dtype

In [ ]:
arr = np.zeros(shape=(6, 2))
arr

In [ ]:
arr1 = np.zeros((6, 2))
arr1

In [ ]:
arr1.size

In [ ]:
arr = np.zeros(shape=(6, 2))
for i in range(6):
    arr[i] = (i, i)
    print(arr[i])

In [ ]:
arr.size

In [ ]:
arr.dtype

#### 3) np.ones()

In [ ]:
np.ones(5)

In [ ]:
np.ones(shape=(6, 2))

In [ ]:
np.ones((5,), dtype=int)

In [ ]:
np.ones((3, 4))

#### 4) np.eye(), np.empty()

In [ ]:
import numpy as np
np.eye(3) # 3x3 크기의 단위 행렬 생성

In [ ]:
np.eye(3, dtype=int)

In [ ]:
# k가 1이므로 대각선 기준으로 하여 1단계 위로 1이 배치
np.eye(3, k=1)

In [ ]:
# k가 1이므로 대각선 기준으로 하여 1단계 아래로 1이 배치
np.eye(3, k=-1)

In [ ]:
np.identity(3)

In [ ]:
import numpy as np
np.empty((2, 2))

In [ ]:
np.empty((2, 2), dtype=int)

In [ ]:
import numpy as np
arr = np.empty((2, 2), dtype=int)
arr

#### 5) np.linspace()
- 구간 내에 숫자를 균일한 간격으로 촘촘하게 채울 수 있는 np.linspace 함수
- np.linspace(구간 시작점, 구간 끝점(끝점 포함), 구간 내 숫자 개수)
  - 끝점을 포함하지 않고 싶으면 endpoint = False
  - retstep = True를 추가하시면 숫자 사이의 간격이 얼마인지에 대한 값을 같이 반환

In [ ]:
import numpy as np
np.linspace(1,10,5)

In [ ]:
import numpy as np
np.linspace(1,10,num=5)

In [ ]:
import numpy as np
np.linspace(1,10)

In [ ]:
np.linspace(2.0, 3.0, num=5)

In [ ]:
# endpoint :지정하지 않으면 True
np.linspace(2.0, 3.0, num=5, endpoint=False)

In [ ]:
# endpoint :지정하지 않으면 True
np.linspace(2.0, 3.0, num=5, endpoint=True)

In [ ]:
import numpy as np
np.linspace(1,2,20)

In [ ]:
import numpy as np
np.linspace(1,2,20, endpoint = False)

In [ ]:
np.linspace(1,2,20, endpoint = False, retstep = True)

In [ ]:
print(np.pi)
print(np.linspace(0, 2))
print(np.linspace(0, 2*np.pi))

#### 6) np.arange()
- 수열을 만들려고 할 때, np.arange 함수를 많이 사용
- np.arange(시작점(생략 시 0), 끝점(미포함), step size(생략 시 1)) 
- range 함수에는 정수 단위만 지원하나, np.arange는 실수 단위도 표현 가능
- range 메소드는 range iterator 자료형을 반환하고, np.arange 메소드는 numpy array 자료형을 반환
- np.arange 메소드 결과는 넘파이에서 수행하는 연산 연계가 가능

In [ ]:
arr = np.arange(5)
arr

In [ ]:
np.arange(1, 5)

In [ ]:
np.arange(1, 10, 2)

In [ ]:
np.arange(5.)

In [ ]:
np.arange(1., 5.)

In [ ]:
np.arange(1, 10.5, 2.5)

In [ ]:
range(5)

In [ ]:
list(range(5))

In [ ]:
range(0, 5, 2)

In [ ]:
arr1 = np.array(range(5))
arr1

In [ ]:
arr1.shape

In [ ]:
import numpy as np

print(np.arange(10))
print(np.arange(1, 15, 2))
print(np.arange(9, -2, -1.5))

In [ ]:
np.arange(1, 5) * 2 # 가능(numpy array 연산)

#### 7) random 서브 모듈
- np.random.seed()과 random.seed()의 또 다른 차이점
  - np.random.seed 함수 내에는 음이 아닌 정수만 seed 값으로 사용될 수 있는 반면에,
    - np.random.seed(10.5) # 불가능
      - (TypeError: Cannot cast scalar from dtype('float64') to dtype('int64') according to the rule 'safe')
    - np.random.seed(-10) # 불가능
      - (ValueError: Seed must be between 0 and 2**32 - 1)
  - random.seed 함수는 실수 범위 내의 숫자들을 모두 seed 값으로 사용할 수 있다.
    - random.seed(10.5) # 가능
    - random.seed(-10) # 가능

In [ ]:
np.random.seed(100) # 같은 시드를 설정하면 동일한 난수가 발생
np.random.rand(5)

In [ ]:
np.random.seed(10) # 같은 시드를 설정하면 동일한 난수가 발생
np.random.rand(5)

In [ ]:
np.random.seed(20)
np.random.rand(5, 3) # 5x3 형태의 2차원 난수 배열 

In [ ]:
np.random.randint(1, 7, size=10) # 1~6사이의 정수 난수 10개 발생

In [ ]:
np.random.randint(1, 11, size=(4, 7)) # 1~10사이의 4x7 형태의 2차원 정수 난수 발생

### << 모집단과 표본표준편차 >>
- 표준편차는 각 측정값과 평균의 차이를 측정하여 해당 자료의 산포도를 나타내는 값.
- 표준 편차란, 평균(mean) 에 대한 오차. 즉, 실제 데이터 값이 평균을 기준으로 할때 얼마나 기복이 있는지를 나타내는 것
- 표준편차의 공식은 자료가 모집단인지 아니면 모집단을 대표하는 표본집단인지에 따라 달라진다.
- 만약 자료가 모집단인 경우, 데이터 값의 개수 N로 나누고, 만약 자료가 모집단을 대표하는 표본집단인 경우, 표본에 있는 자료값의 개수보다 작은 N−1로 나눈다.

![표준편차](./표준편차.png)

#### 모표준편차 구하기
    - 1 단계: 주어진 자료의 평균을 구합니다. 
    - 2 단계: 주어진 측정값에서 평균을 뺀 만큼을 편차라 부릅니다. 편차의 값은 음수나 양수가 될 수도 있다.
    - 3 단계: 모든 편차를 제곱하여 양수로 만든다.
    - 4 단계: 제곱된 편차들을 모두 더한다.
    - 5 단계: 제곱된 편차의 합을 모집단에 있는 자료의 개수로 나눈다. 이 단계에서 나온 값을 분산이라 함.
    - 6 단계: 분산에 제곱근을 씌워 표준편차를 구한다.

#### 표본표준편차 구하기

    - 1 단계: 주어진 자료의 평균을 구하고 
    - 2 단계: 주어진 측정값에서 평균을 뺀 만큼을 편차라 함. 편차의 값은 음수나 양수가 될 수도 있다.
    - 3 단계: 모든 편차를 제곱하여 양수로 만든다.
    - 4 단계: 제곱된 편차들을 모두 더한다.
    - 5 단계: 제곱된 편차들의 합을 표본집단의 자료 개수에서 하나를 뺀 값으로 나눈다. 이 단계에서 나온 값을 분산이라고 함
    - 6 단계: 분산에 제곱근을 씌워 표준편차를 구한다.

In [ ]:
# 10명의 키를 난수로 생성. 평균은 170cm, 표준편차는 10인 정규분포
np.random.seed(100)
m = 170 
sigma = 10 
heights = m+sigma*np.random.randn(10)  
heights

In [ ]:
# 10000명의 키를 난수로 생성. 평균은 175cm, 표준편차는 10인 정규분포
m = 175 
sigma = 10 
heights = m+sigma*np.random.randn(10000)  
heights

In [ ]:
# 12명의 키를 난수로 생성. 평균은 175cm, 표준편차는 10인 정규분포

np.random.seed(100) # 같은 시드를 설정하면 동일한 난수가 발생
m = 175 
sigma = 10 
heights = m+sigma*np.random.randn(12)  
heights

In [ ]:
# 평균값이 175, 표준편차가 10인 정규 분포 함수 생성 
np.random.seed(100) # 같은 시드를 설정하면 동일한 난수가 발생
nums = np.random.normal(loc=175, scale=10, size=(3, 4)).round(2)
nums

In [ ]:
# 평균값이 165, 표준편차가 10인 정규 분포 함수 생성 
nums = np.random.normal(loc=165, scale=10, size=(3, 4)).round(2)
nums

In [ ]:
import numpy as np
list1 = [1, 2, 3]
list2 = [4, 5, 6]
print(list1 + list2)
print('--------')
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(arr1 + arr2)

### reshape()
- 넘파이 배열의 차원을 변환

In [ ]:
import numpy as np
arr = np.array([1, 2, 3])
arr

In [ ]:
arr = np.arange(12).reshape(3,4)
arr

In [ ]:
arr.shape

In [ ]:
print(arr.reshape(-1))
arr1 = arr.reshape(-1)
arr1

In [ ]:
arr.shape

In [ ]:
arr1.shape

In [ ]:
arr.reshape(-1, 2)

In [ ]:
arr.reshape(3, -1)

### 넘파이 배열 인덱싱 & 슬라이싱

In [ ]:
arr1 = np.arange(10)
print(arr1,'\n')
print(arr1[1])
print(arr1[:6])
print(arr1[0:5],'\n')
print(arr1[::2])
print(arr1[1::2])
print(arr1[1:7:2],'\n')
print(arr1[-3:9])
print(arr1[:-3])
print(arr1[-3:2:-1],'\n')
print(arr1[5:2])
print(arr1[5:])
print(arr2[1:])

In [ ]:
import numpy as np
arr = np.arange(10)
print(arr)
arr[0] = 100
print(arr)
print('------------')
arr1 = arr[3:7]
print(arr1)
print('------------')
arr1[:] = 90
print(arr1)
print(arr)

In [ ]:
arr2 = np.arange(9).reshape(3, 3)
print(arr2)
print('--------')
print(arr2[0:2, 0:2])

In [ ]:
arr2 = np.arange(9).reshape(3, 3)
print(arr2,'\n')
print(arr2[2, 1])
print(arr2[:2, :2])
print(arr2[:, ::-1],'\n')
print(arr2[:, :])
print(arr2[1, :])
print(arr2[1,2])

In [ ]:
arr3 = np.reshape(np.arange(24), (2, 3, 4))
print(arr3,'\n')
print(arr3[1,1,2])
print(arr3[1][2][3])
print(arr3[0, :, 1],'\n')
print(arr3[1, :, :],'\n')
print(arr3[:2, 1:, :2])

### 배열 연산

In [ ]:
import numpy as np
ages = np.array([18, 19, 25, 30, 28])
y = ages > 20
print(y)
print(ages[ages > 20])

In [ ]:
np_array = np.array([[1,2,3], [4,5,6], [7,8,9]])
np_array > 5

In [ ]:
np_array[np_array > 5]

In [ ]:
np_array[(np_array > 3) & (np_array < 8)]

In [ ]:
np_array[:, 2] > 5

In [ ]:
np_array[:, 2]

In [ ]:
import numpy as np 

players = [[170, 76.4], 
           [183, 86.2], 
           [181, 78.5], 
           [176, 80.1]] 

np_players = np.array(players) 

print('몸무게가 80 이상인 선수 정보');
print(np_players[ np_players[:, 1] >= 80.0 ])

print('키가 175 이상인 선수 정보');
print(np_players[ np_players[:, 0] >= 175.0 ])

In [ ]:
# 키가 180이상이면서 몸무게가 80이상인 선수 추출
import numpy as np 

players = [[170, 76.4], 
           [183, 86.2], 
           [181, 78.5], 
           [176, 80.1]] 
np_players = np.array(players)
print( np_players[(np_players[:, 0] >= 180.0)  &  (np_players[:, 1] >= 80.0)])

In [ ]:
import numpy as np
num = np.array([18, -2, -5, 30, 28])
# num 수가 0미만이면 0으로 변경, 그렇지 않으면 원래 값으로 대입
p_num = np.where(num < 0, 0, num) 
print(p_num)
print(p_num.sum())

In [ ]:
import numpy as np 
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
print(arr1 + arr2)
print('----------')
print(arr1 - arr2)
print('----------')
print(arr1 * arr2)
print('----------')
print(arr1 / arr2)

In [ ]:
import numpy as np 
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
print(np.add(arr1, arr2))
print('----------')
print(np.subtract(arr1, arr2))
print('----------')
print(np.multiply(arr1, arr2))
print('----------')
print(np.divide(arr1, arr2))

In [ ]:
array_data = np.array([ 3, 7, 1, 2, 21])
np.mean(array_data)

In [ ]:
len(array_data)

In [ ]:
np.median(array_data)

In [ ]:
np.max(array_data)

In [ ]:
np.min(array_data)

In [ ]:
np.sum(array_data)

In [ ]:
# 브로드캐스팅(Broadcasting)
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a*5)
print(b+5)
print(a+b)
print(a*b)
print(b-a)
print(b/a)

In [ ]:
import numpy as np
a = np.array([[1, 2], [3, 4]])
b = np.array([5, 10])
print(a+b)
print(a*b)